apiVersion: apps/v1
kind: Deployment
metadata:
  name: finances
  namespace: finances
  labels:
    app: finances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finances
  template:
    metadata:
      labels:
        app: finances
    spec:
      containers:
      - name: finances
        image: tiquinhonew/finances:7df75a6830189bd220f87d40224a3c89fe690290
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: finances-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
