apiVersion: apps/v1
kind: Deployment
metadata:
  name: finances
  namespace: finances
  labels:
    app: finances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finances
  template:
    metadata:
      labels:
        app: finances
    spec:
      containers:
      - name: finances
        image: tiquinhonew/finances:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: API_URL
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: FRONTEND_URL
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MAIL_HOST
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MAIL_PASSWORD
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MAIL_PORT
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MAIL_USERNAME
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MYSQL_HOST
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: MYSQL_USER
        - name: SERVER_PORT
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: SERVER_PORT
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: TWILIO_PHONE_NUMBER
        - name: TWILIO_SERVICE_SID
          valueFrom:
            secretKeyRef:
              name: finances-secrets
              key: TWILIO_SERVICE_SID
