apiVersion: apps/v1
kind: Deployment
metadata:
  name: finances
  namespace: finances
  labels:
    app: finances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finances
  template:
    metadata:
      labels:
        app: finances
    spec:
      containers:
      - name: finances
        image: tiquinhonew/finances:ede964bcc1b3ca391e1f6d78d858611073a2d770
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: finances-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
