apiVersion: apps/v1
kind: Deployment
metadata:
  name: impostor-game
  namespace: impostor-game
  labels:
    app: impostor-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impostor-game
  template:
    metadata:
      labels:
        app: impostor-game
    spec:
      containers:
      - name: impostor-game
        image: tiquinhonew/impostor-game:db7a7b0aeffc448efe946d367857e1fce8dba95f
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: impostor-game-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
