apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: impostor-game-ingress
  namespace: impostor-game
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "impostor-game.app.purplebit.com.br"
    secretName: impostor-game-tls
  rules:
  - host: impostor-game.app.purplebit.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: impostor-game
            port:
              number: 80
