apiVersion: v1
kind: Service
metadata:
  name: impostor-game
  namespace: impostor-game
  labels:
    app: impostor-game
spec:
  selector:
    app: impostor-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
